classes: {
    d: {
        style: {
            stroke-dash: 3
            border-radius: 5
        }
    }
}

user: ""
user.class: d
user.text: |md
Primary Level of User Engagement
- search for concent
- access individual documents for georeferencing
|

user.map1: ""
user.map1.text: |md
#### Simple Map
- a single scanned document
|

doc1: Document 1

user.map1 -> doc1

lyr1: Layer 1

doc1 -> lyr1

